name: Debug
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      run: |
        echo ${{ secrets.PASSWORD }}  
        echo ${{ secrets.USERNAME }}  
        echo ${{ secrets.IP_ADDRESS }}


